import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';

@Injectable({
  providedIn: 'root'
})
export class ChordsService {
  constructor() { }

  getChordsType() {
    return of([
      'fifth',
      'major',
      'minor',
      'suspended 2nd',
      'suspended 4th',
      'Mb5',
      'diminished',
      'augmented',
      'm#5',
      '7no5',
      'Mb6',
      'sixth',
      'major seventh',
      'major seventh b6',
      'minor seventh',
      'minor/major seventh',
      'minor sixth',
      'diminished seventh',
      'half-diminished',
      'dominant seventh',
      'altered',
      'suspended 4th seventh',
      'augmented seventh',
      'sus24',
      '7#5',
      '+add#9',
      'M#5add9',
      'Madd9',
      'Maddb9',
      'M7b5',
      '7b5',
      '9no5',
      'madd4',
      'madd9',
      'oM7',
      'm7b5',
      'mb6M7',
      'm7#5',
      'mb6b9',
      '7#5sus4',
      'M7sus4',
      'M7#5sus4',
      '4',
      '7b13',
      'major ninth',
      'sixth/ninth',
      'minor ninth',
      'dominant ninth',
      'dominant b9',
      'dominant #9',
      'lydian',
      'lydian dominant seventh',
      'suspended 4th b9',
      'dominant #9',
      'Maj9#5',
      '7#5#9',
      '9#5',
      '7#5b9',
      'M7b9',
      '7b6',
      'M9b5',
      '9b5',
      'm69',
      'mMaj7b6',
      'mMaj9',
      'o7M7',
      'm9#5',
      'M9#5sus4',
      'M9sus4',
      '9sus4',
      'eleventh',
      '13no5',
      '9b13',
      '11b9',
      'M6#11',
      '7add6',
      'm7add11',
      'm9b5',
      'M7add13',
      '7b9#9',
      '13b5',
      'mMaj9b6',
      'major thirteenth',
      'minor eleventh',
      'minor thirteenth',
      'dominant thirteenth',
      '13#9',
      'maj7#9#11',
      'major #11 (lydian)',
      '9#5#11',
      '7#5b9#11',
      '69#11',
      '7#9#11',
      '7#9b13',
      '9#11',
      '7b9#11',
      '13b9',
      '7b9b13',
      'm11A',
      'm11b5',
      '13sus4',
      '7sus4b9b13',
      '7#11b13',
      '13#9#11',
      '7#9#11b13',
      '13#11',
      '9#11b13',
      '13b9#11',
      '7b9b13#11',
      'M13#11'
    ]);
  }
}
